### ISSUE TITLE
Code is not able to determine the message from own user versus other participent

### ISSUE THREAD

**Issue by nbaua** [IncredibleWeb/Xamarin-Forms-Chat-Client#3]
Hi,

The code is excellent and working nicely except the thing, the code has to be tweaked at places to work correctly. It is showing bubbles with a lump logic of IsMine flag in ChatViewModel.cs simply divisible by 2

> `_messages.Add (new ChatMessageViewModel{ Name=e.Name,Message=e.Message,IsMine=_messages.Count%2==0 });`

This could be better with the correct logic in place for the new users who are trying to learn from your code.

I do not mean to be rude or not suggesting this ironically, I came across this post via XF forum and found you as a avid user who loves to share and help the community as I do. So though would be nice to prompt you to take some of your valuable time and update the code. I could have forked it and did it, however I want all your hard-work remain with  your credits. so just take this not so ISSUE as a suggestion. Thanks,

N Baua

**Comment by shaungrech** [comment]
Hi N Baua,

Thank you for your feedback. The idea of this code was to show that it is possible to display a list of bubbles distinguishing between senders and receivers. The code you quotes was there to make sure we have some of both.

Please feel free to close the issue and open a Pull request so that I may review and close. I appreciate your feedback.

Shaun

**Comment by nbaua** [comment]
Okey
